// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTgbmOMwPPWf96OD-MQt-Zxok-ObtHtFY',
    appId: '1:999287031151:web:c6a68706f218bd5b15549a',
    messagingSenderId: '999287031151',
    projectId: 'social-media-app-test-a215d',
    authDomain: 'social-media-app-test-a215d.firebaseapp.com',
    storageBucket: 'social-media-app-test-a215d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Xu1b6nKXZQFuegQeKJohNFUz9AzudQs',
    appId: '1:999287031151:android:d844c4e5575ff3a415549a',
    messagingSenderId: '999287031151',
    projectId: 'social-media-app-test-a215d',
    storageBucket: 'social-media-app-test-a215d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD21ACpVI_lsFsSFzrBSolNY_whJtNiPTQ',
    appId: '1:999287031151:ios:e5c69a05710b3ddd15549a',
    messagingSenderId: '999287031151',
    projectId: 'social-media-app-test-a215d',
    storageBucket: 'social-media-app-test-a215d.firebasestorage.app',
    iosBundleId: 'com.example.globally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD21ACpVI_lsFsSFzrBSolNY_whJtNiPTQ',
    appId: '1:999287031151:ios:e5c69a05710b3ddd15549a',
    messagingSenderId: '999287031151',
    projectId: 'social-media-app-test-a215d',
    storageBucket: 'social-media-app-test-a215d.firebasestorage.app',
    iosBundleId: 'com.example.globally',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTgbmOMwPPWf96OD-MQt-Zxok-ObtHtFY',
    appId: '1:999287031151:web:6299fb9c1f1b906c15549a',
    messagingSenderId: '999287031151',
    projectId: 'social-media-app-test-a215d',
    authDomain: 'social-media-app-test-a215d.firebaseapp.com',
    storageBucket: 'social-media-app-test-a215d.firebasestorage.app',
  );
}
